parameters:
  ongr_api.data_request.class: ONGR\ApiBundle\Service\DataRequestService

services:
    ongr_api.api_doc.extractor:
            class: ONGR\ApiBundle\Service\NelmioExtractor
            calls:
                - [ setContainer, [ @service_container ] ]
            tags:
                - { name: nelmio_api_doc.extractor.handler }

    ongr_api.route_loader:
        class: ONGR\ApiBundle\Routing\ApiRouteLoader
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: routing.loader }

#  ongr_api.api.[version].[endpoint].controller
#  ongr_api.api.[version].[endpoint].data_request
#  ongr_api.api.[version].[endpoint].router
